---
# tasks file for jboss-widlfly
- name: get user home directory
  shell: >
    getent passwd `whoami` | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Make a directory for source checkouts
  file:
    path: "{{ user_home.stdout }}/src"
    state: directory

- name: get the java version
  shell: >
    java -version 
  register: java_version
  ignore_errors: true
  

- name: print java version
  debug:
    msg: "Java Version: {{ java_version }}"
  when: java_version.rc==0

- name: Install openjdk 1.8 and dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items: 
    - java-1.8.0-openjdk
  become: yes
  when: java_version.rc!=0

- name: Check if wildfly executable exists
  stat:
    path: "{{ user_home.stdout }}/src/wildfly-22.0.1.Final.tar.gz"
  register: file_stat

- name: Download wildfly v.22.0.1
  get_url:
    url: "https://download.jboss.org/wildfly/22.0.1.Final/wildfly-22.0.1.Final.tar.gz"
    dest: "{{ user_home.stdout }}/src/wildfly-22.0.1.Final.tar.gz"
  when: not file_stat.stat.exists


- name: Extract wildfly 
  unarchive:
    src: "{{ user_home.stdout }}/src/wildfly-22.0.1.Final.tar.gz"
    dest: "{{ user_home.stdout }}/src"
    remote_src: yes
  when: not file_stat.stat.exists


- name: Set JBoss/Wildfly home
  lineinfile:
    path: "{{ user_home.stdout }}/src/wildfly-22.0.1.Final/bin/standalone.conf"
    line: "export JBOSS_HOME={{ user_home.stdout }}/src/wildfly-22.0.1.Final"
    state: present


- name: Start JBoss server
  command:
    cmd: "./standalone.sh"
    chdir: "{{ user_home.stdout }}/src/wildfly-22.0.1.Final/bin"